language: python
before_install:
- openssl aes-256-cbc -K $encrypted_ce6702f73085_key -iv $encrypted_ce6702f73085_iv -in .travis/config.yml.enc -out .travis/config.yml -d
install:
- pip install -r requirements.txt
script:
- ./zdownload.py -h
- ./zdownload.py -c 42 --config .travis/config.yml
- ./zdownload.py --config .travis/config.yml
- if [ `find ~/zendesk/42_None -name "cl_support*" -type d | wc -l` -ne 4 ]; then exit 1; fi
- if [ `find ~/zendesk/42_None -name "*.gz" | wc -l` -ne 0 ]; then exit 1; fi
